CREATE TABLE  "DEPARTMENTS" 
   (	"ID" NUMBER(*,0), 
	"NAME" VARCHAR2(50), 
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   )
/
CREATE TABLE  "PERSONS" 
   (	"ID" NUMBER(*,0), 
	"NAME" VARCHAR2(50), 
	"EMAIL" VARCHAR2(50), 
	"NASTERE" DATE, 
	"SEX" CHAR(1), 
	"DEP_ID" NUMBER(*,0), 
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   )
/
ALTER TABLE  "PERSONS" ADD CONSTRAINT "DEPARTMENT_ID" FOREIGN KEY ("DEP_ID")
	  REFERENCES  "DEPARTMENTS" ("ID") ENABLE
/
